/**
 * Manifest entries for the remaining tracks in `AdventureTrackType` order
 * (ORBITAL_JUNKYARD → POLYCHROME_VOID). Assembled into `MANIFEST_DATA` by
 * `track-manifest-data.ts`; see that file for the registration contract.
 */

import { AdventureTrackType } from '../adventure-types'
import type { TrackManifest } from './track-manifest-types'

export const EXTENDED_MANIFEST_DATA: TrackManifest[] = [
  {
    id: AdventureTrackType.ORBITAL_JUNKYARD,
    startAnchor: { x: 0, y: 15, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/orbital-junkyard').then((m) => m.buildOrbitalJunkyard),
    zone: {
      name: 'Orbital Junkyard',
      storyText: 'ORBITAL DEBRIS FIELD\n\nNavigate the scrap sector...',
      videoUrl: 'videos/zones/junkyard_intro.mp4',
      musicTrackId: 'orbital-junkyard',
      primaryColor: '#aaaaaa',
      accentColor: '#ff6600',
      interiorColor: '#cccccc',
      isMajorTransition: true,
      glowIntensity: 0.9,
    },
  },
  {
    id: AdventureTrackType.FIREWALL_BREACH,
    startAnchor: { x: 0, y: 25, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/FIREWALL_BREACH.json',
    zone: {
      name: 'Firewall Breach',
      storyText: 'WARNING: SECURITY BREACH\n\nIntrusion detected...',
      videoUrl: 'videos/zones/firewall_intro.mp4',
      musicTrackId: 'firewall-breach',
      primaryColor: '#ff0000',
      accentColor: '#ffaa00',
      interiorColor: '#ff4444',
      isMajorTransition: true,
      glowIntensity: 1.7,
    },
    catalog: {
      description: 'Campaign finale — punch through two security layers to reach root access.',
      difficulty: 'expert',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 120000,
      timeLimitSeconds: 165,
      timeoutPenaltyMultiplier: 0.36,
      unlockedBy: 'CASINO_HEIST',
      theme: 'firewall',
      visualTheme: { primary: 'ALERT', accent: 'CYAN', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.CPU_CORE,
    startAnchor: { x: 0, y: 15, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/cpu-core').then((m) => m.buildCpuCore),
    zone: {
      name: 'CPU Core',
      storyText: 'ENTERING: CPU CORE\n\nThe central processor awaits...',
      videoUrl: 'videos/zones/cpu_intro.mp4',
      musicTrackId: 'cpu-core',
      primaryColor: '#00ff00',
      accentColor: '#88ff00',
      interiorColor: '#44ff44',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
  },
  {
    id: AdventureTrackType.CRYO_CHAMBER,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/CRYO_CHAMBER.json',
    zone: {
      name: 'Cryo Chamber',
      storyText: 'CRYOGENIC ZONE\n\nTemperature dropping...',
      videoUrl: 'videos/zones/cryo_intro.mp4',
      musicTrackId: 'cryo-chamber',
      primaryColor: '#00ccff',
      accentColor: '#ffffff',
      interiorColor: '#88ddff',
      isMajorTransition: true,
      glowIntensity: 1.2,
    },
    catalog: {
      description: 'Near-frictionless ice — a slalom of pillars and an avalanche sweep.',
      difficulty: 'expert',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 95000,
      timeLimitSeconds: 150,
      timeoutPenaltyMultiplier: 0.40,
      unlockedBy: 'CHRONO_CORE',
      theme: 'cryo',
      visualTheme: { primary: 'WHITE', accent: 'CYAN', surfaceTint: 'GLASS' },
    },
  },
  {
    id: AdventureTrackType.BIO_HAZARD_LAB,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/bio-hazard-lab').then((m) => m.buildBioHazardLab),
    zone: {
      name: 'Bio Hazard Lab',
      storyText: 'BIOHAZARD WARNING\n\nToxic materials present...',
      videoUrl: 'videos/zones/biohazard_intro.mp4',
      musicTrackId: 'bio-hazard',
      primaryColor: '#44ff00',
      accentColor: '#ffcc00',
      interiorColor: '#66ff22',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
  },
  {
    id: AdventureTrackType.GRAVITY_FORGE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/gravity-forge').then((m) => m.buildGravityForge),
    zone: {
      name: 'Gravity Forge',
      storyText: 'GRAVITY FORGE\n\nHeavy industry sector...',
      videoUrl: 'videos/zones/forge_intro.mp4',
      musicTrackId: 'gravity-forge',
      primaryColor: '#ff6600',
      accentColor: '#ffcc00',
      interiorColor: '#ff8844',
      isMajorTransition: true,
      glowIntensity: 1.5,
    },
  },
  {
    id: AdventureTrackType.TIDAL_NEXUS,
    startAnchor: { x: 0, y: 25, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/TIDAL_NEXUS.json',
    zone: {
      name: 'Tidal Nexus',
      storyText: 'TIDAL NEXUS\n\nFlow with the current...',
      videoUrl: 'videos/zones/tidal_intro.mp4',
      musicTrackId: 'tidal-nexus',
      primaryColor: '#0088ff',
      accentColor: '#00ffcc',
      interiorColor: '#44aaff',
      isMajorTransition: false,
      glowIntensity: 1.2,
    },
    catalog: {
      description: 'Post-finale spillway — turbine spin, riptide bank, and an abyssal drop basin.',
      difficulty: 'expert',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 125000,
      timeLimitSeconds: 170,
      timeoutPenaltyMultiplier: 0.35,
      unlockedBy: 'FIREWALL_BREACH',
      theme: 'tidal',
      visualTheme: { primary: 'CYAN', accent: 'WHITE', surfaceTint: 'GLASS' },
    },
  },
  {
    id: AdventureTrackType.DIGITAL_ZEN_GARDEN,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/DIGITAL_ZEN_GARDEN.json',
    zone: {
      name: 'Digital Zen Garden',
      storyText: 'ZEN GARDEN\n\nFind your center...',
      videoUrl: 'videos/zones/zen_intro.mp4',
      musicTrackId: 'zen-garden',
      primaryColor: '#88ffaa',
      accentColor: '#ff88aa',
      interiorColor: '#aaffcc',
      isMajorTransition: false,
      glowIntensity: 0.8,
    },
    catalog: {
      description: 'Raked sand lanes, a low-friction stream bend, and a moon-bridge shrine basin.',
      difficulty: 'medium',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 60000,
      timeLimitSeconds: 110,
      timeoutPenaltyMultiplier: 0.48,
      unlockedBy: 'SOLAR_FLARE',
      theme: 'zen',
      visualTheme: { primary: 'WHITE', accent: 'MAGENTA', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.SYNTHWAVE_SURF,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/synthwave-surf').then((m) => m.buildSynthwaveSurf),
    zone: {
      name: 'Synthwave Surf',
      storyText: 'SURF THE WAVES\n\nCatch the perfect break...',
      videoUrl: 'videos/zones/surf_intro.mp4',
      musicTrackId: 'synthwave-surf',
      primaryColor: '#ff88cc',
      accentColor: '#00ddff',
      interiorColor: '#ffaadd',
      isMajorTransition: false,
      glowIntensity: 1.1,
    },
  },
  {
    id: AdventureTrackType.SOLAR_FLARE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/SOLAR_FLARE.json',
    zone: {
      name: 'Solar Flare',
      storyText: 'WARNING: SOLAR FLARE\n\nRadiation levels high...',
      videoUrl: 'videos/zones/solar_intro.mp4',
      musicTrackId: 'solar-flare',
      primaryColor: '#ffaa00',
      accentColor: '#ff4400',
      interiorColor: '#ffcc44',
      isMajorTransition: true,
      glowIntensity: 1.6,
    },
    catalog: {
      description: 'Coronal launch, sunspot straight, and a solar-wind sweep into the fusion core.',
      difficulty: 'hard',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 115000,
      timeLimitSeconds: 155,
      timeoutPenaltyMultiplier: 0.36,
      unlockedBy: 'TIDAL_NEXUS',
      theme: 'solar',
      visualTheme: { primary: 'GOLD', accent: 'ALERT', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.PRISM_PATHWAY,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/prism-pathway').then((m) => m.buildPrismPathway),
    zone: {
      name: 'Prism Pathway',
      storyText: 'PRISM PATHWAY\n\nLight refracts infinitely...',
      videoUrl: 'videos/zones/prism_intro.mp4',
      musicTrackId: 'prism-path',
      primaryColor: '#ff00ff',
      accentColor: '#00ffff',
      interiorColor: '#ff88ff',
      isMajorTransition: true,
      glowIntensity: 1.5,
    },
  },
  {
    id: AdventureTrackType.MAGNETIC_STORAGE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/magnetic-storage').then((m) => m.buildMagneticStorage),
    zone: {
      name: 'Magnetic Storage',
      storyText: 'MAGNETIC STORAGE\n\nData streams flowing...',
      videoUrl: 'videos/zones/magnetic_intro.mp4',
      musicTrackId: 'magnetic',
      primaryColor: '#aa44ff',
      accentColor: '#00ff88',
      interiorColor: '#cc88ff',
      isMajorTransition: false,
      glowIntensity: 1.2,
    },
  },
  {
    id: AdventureTrackType.NEURAL_NETWORK,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/neural-network').then((m) => m.buildNeuralNetwork),
    zone: {
      name: 'Neural Network',
      storyText: 'NEURAL NETWORK\n\nSynaptic pathways active...',
      videoUrl: 'videos/zones/neural_intro.mp4',
      musicTrackId: 'neural',
      primaryColor: '#ff66aa',
      accentColor: '#aa66ff',
      interiorColor: '#ff99cc',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
  },
  {
    id: AdventureTrackType.NEON_STRONGHOLD,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/neon-stronghold').then((m) => m.buildNeonStronghold),
    zone: {
      name: 'Neon Stronghold',
      storyText: 'NEON STRONGHOLD\n\nThe fortress awaits...',
      videoUrl: 'videos/zones/stronghold_intro.mp4',
      musicTrackId: 'stronghold',
      primaryColor: '#00aaff',
      accentColor: '#ff00cc',
      interiorColor: '#44ccff',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'Optional siege route — drawbridges and portcullis gates ring the courtyard.',
      difficulty: 'hard',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 55000,
      timeLimitSeconds: 95,
      timeoutPenaltyMultiplier: 0.45,
      unlockedBy: 'PACHINKO_HALL',
      theme: 'fortress',
      visualTheme: { primary: 'PURPLE', accent: 'GOLD', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.CASINO_HEIST,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/casino-heist').then((m) => m.buildCasinoHeist),
    zone: {
      name: 'Casino Heist',
      storyText: 'CASINO HEIST\n\nHigh stakes ahead...',
      videoUrl: 'videos/zones/casino_intro.mp4',
      musicTrackId: 'casino',
      primaryColor: '#ffcc00',
      accentColor: '#ff0044',
      interiorColor: '#ffdd44',
      isMajorTransition: true,
      glowIntensity: 1.5,
    },
    catalog: {
      description: 'Chip stacks, a live roulette wheel, and slot gates guarding the vault.',
      difficulty: 'expert',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 105000,
      timeLimitSeconds: 90,
      timeoutPenaltyMultiplier: 0.38,
      unlockedBy: 'CRYO_CHAMBER',
      theme: 'casino',
      visualTheme: { primary: 'GOLD', accent: 'ALERT', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.TESLA_TOWER,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/tesla-tower').then((m) => m.buildTeslaTower),
    zone: {
      name: 'Tesla Tower',
      storyText: 'TESLA TOWER\n\nHigh voltage zone...',
      videoUrl: 'videos/zones/tesla_intro.mp4',
      musicTrackId: 'tesla',
      primaryColor: '#aa66ff',
      accentColor: '#00ffff',
      interiorColor: '#cc99ff',
      isMajorTransition: true,
      glowIntensity: 1.6,
    },
  },
  {
    id: AdventureTrackType.NEON_SKYLINE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/neon-skyline').then((m) => m.buildNeonSkyline),
    zone: {
      name: 'Neon Skyline',
      storyText: 'NEON SKYLINE\n\nThe city never sleeps...',
      videoUrl: 'videos/zones/skyline_intro.mp4',
      musicTrackId: 'skyline',
      primaryColor: '#0088ff',
      accentColor: '#ff00aa',
      interiorColor: '#44aaff',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
  },
  {
    id: AdventureTrackType.POLYCHROME_VOID,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/polychrome-void').then((m) => m.buildPolychromeVoid),
    zone: {
      name: 'Polychrome Void',
      storyText: 'THE POLYCHROME VOID\n\nBeyond the spectrum...',
      videoUrl: 'videos/zones/polychrome_intro.mp4',
      musicTrackId: 'polychrome',
      primaryColor: '#ffffff',
      accentColor: '#ff00ff',
      interiorColor: '#f0f0f0',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'A colour-logic arena — chroma gates only pass the matching ball state.',
      difficulty: 'hard',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 75000,
      timeLimitSeconds: 95,
      timeoutPenaltyMultiplier: 0.44,
      unlockedBy: 'RETRO_WAVE_HILLS',
      theme: 'chroma-puzzle',
      visualTheme: { primary: 'WHITE', accent: 'MAGENTA', surfaceTint: 'GLASS' },
    },
  },
]
