/**
 * Manifest entries for the first eleven tracks in `AdventureTrackType` order
 * (NEON_HELIX → PACHINKO_SPIRE). Assembled into `MANIFEST_DATA` by
 * `track-manifest-data.ts`; see that file for the registration contract.
 */

import { AdventureTrackType } from '../adventure-types'
import type { TrackManifest } from './track-manifest-types'

export const CORE_MANIFEST_DATA: TrackManifest[] = [
  {
    id: AdventureTrackType.NEON_HELIX,
    startAnchor: { x: 0, y: 2, z: 8 },
    buildKind: 'json',
    dataPath: './track-data/NEON_HELIX.json',
    zone: {
      name: 'Neon Helix',
      storyText: 'ENTERING: NEON HELIX\n\nThe spiral descent begins...',
      videoUrl: 'videos/zones/neon_helix_intro.mp4',
      musicTrackId: 'neon-helix',
      primaryColor: '#00d9ff',
      accentColor: '#ff00aa',
      interiorColor: '#00ffff',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
    catalog: {
      description: 'A classic descent through spiraling neon light. Perfect for beginners.',
      difficulty: 'easy',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 50000,
      timeLimitSeconds: 120,
      timeoutPenaltyMultiplier: 0.55,
      theme: 'cyber-neon',
      visualTheme: { primary: 'CYAN', accent: 'MAGENTA', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.PACHINKO_HALL,
    startAnchor: { x: 0, y: 8, z: 4 },
    buildKind: 'ts',
    loadBuilder: () => import('../tracks/pachinko-hall').then((m) => m.buildPachinkoHall),
    zone: {
      name: 'Pachinko Hall',
      storyText: 'ENTERING: PACHINKO HALL\n\nThe neon parlor opens — follow the pin lanes to the exit arch...',
      videoUrl: 'videos/zones/pachinko_hall_intro.mp4',
      musicTrackId: 'pachinko-hall',
      primaryColor: '#ffdd00',
      accentColor: '#ff66cc',
      interiorColor: '#ffaa00',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'A neon parlor corridor — pin lanes, conveyor currents, and machine alcoves lead to the exit arch.',
      difficulty: 'easy',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 40000,
      timeLimitSeconds: 100,
      timeoutPenaltyMultiplier: 0.50,
      unlockedBy: 'NEON_HELIX',
      theme: 'pachinko-neon',
      visualTheme: { primary: 'GOLD', accent: 'MAGENTA', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.CYBER_CORE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/CYBER_CORE.json',
    zone: {
      name: 'Cyber Core',
      storyText: 'ENTERING: CYBER CORE\n\nDescending into the digital depths...',
      videoUrl: 'videos/zones/cyber_core_intro.mp4',
      musicTrackId: 'cyber-core',
      primaryColor: '#8800ff',
      accentColor: '#00d9ff',
      interiorColor: '#aa44ff',
      isMajorTransition: true,
      glowIntensity: 1.1,
    },
    catalog: {
      description: 'Fast-paced vertical descent through a digital core. Requires precision timing.',
      difficulty: 'medium',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 45000,
      timeLimitSeconds: 90,
      timeoutPenaltyMultiplier: 0.45,
      unlockedBy: 'PACHINKO_HALL',
      theme: 'digital',
      visualTheme: { primary: 'MAGENTA', accent: 'CYAN', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.QUANTUM_GRID,
    startAnchor: { x: 0, y: 10, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/QUANTUM_GRID.json',
    zone: {
      name: 'Quantum Grid',
      storyText: 'ENTERING: QUANTUM GRID\n\nNavigate the probability maze...',
      videoUrl: 'videos/zones/quantum_grid_intro.mp4',
      musicTrackId: 'quantum-grid',
      primaryColor: '#00ff44',
      accentColor: '#ffffff',
      interiorColor: '#88ffaa',
      isMajorTransition: true,
      glowIntensity: 1.5,
    },
    catalog: {
      description: 'Navigate a complex maze of quantum pathways. The ultimate puzzle challenge.',
      difficulty: 'hard',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 80000,
      timeLimitSeconds: 150,
      timeoutPenaltyMultiplier: 0.50,
      unlockedBy: 'CYBER_CORE',
      theme: 'quantum',
      visualTheme: { primary: 'PURPLE', accent: 'WHITE', surfaceTint: 'GLASS' },
    },
  },
  {
    id: AdventureTrackType.STORM_LATTICE,
    startAnchor: { x: 0, y: 30, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/STORM_LATTICE.json',
    zone: {
      name: 'Storm Lattice',
      storyText: 'ENTERING: STORM LATTICE\n\nUpdrafts howl through the pin grid...',
      musicTrackId: 'storm-lattice',
      primaryColor: '#44ccff',
      accentColor: '#ffffff',
      interiorColor: '#88ddff',
      isMajorTransition: false,
      glowIntensity: 1.3,
    },
    catalog: {
      description: 'A storm-lashed pachinko board — updraft shafts loft the ball back into the pins before crosswinds herd it home.',
      difficulty: 'hard',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 90000,
      timeLimitSeconds: 120,
      timeoutPenaltyMultiplier: 0.45,
      unlockedBy: 'QUANTUM_GRID',
      theme: 'storm',
      visualTheme: { primary: 'CYAN', accent: 'WHITE', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.SINGULARITY_WELL,
    startAnchor: { x: 0, y: 25, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/SINGULARITY_WELL.json',
    zone: {
      name: 'Singularity Well',
      storyText: 'WARNING: GRAVITY ANOMALY\n\nApproaching event horizon...',
      videoUrl: 'videos/zones/singularity_intro.mp4',
      musicTrackId: 'singularity-well',
      primaryColor: '#ff4400',
      accentColor: '#ff0000',
      interiorColor: '#ff6622',
      isMajorTransition: true,
      glowIntensity: 1.6,
    },
    catalog: {
      description: 'Enter a black hole. Gravity pulls everything inward. Expert only.',
      difficulty: 'expert',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 100000,
      timeLimitSeconds: 180,
      timeoutPenaltyMultiplier: 0.35,
      unlockedBy: 'STORM_LATTICE',
      theme: 'cosmic',
      visualTheme: { primary: 'ALERT', accent: 'AMBIENT', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.GLITCH_SPIRE,
    startAnchor: { x: 0, y: 10, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/GLITCH_SPIRE.json',
    zone: {
      name: 'Glitch Spire',
      storyText: 'ALERT: REALITY UNSTABLE\n\nGlitch corruption detected...',
      videoUrl: 'videos/zones/glitch_spire_intro.mp4',
      musicTrackId: 'glitch-spire',
      primaryColor: '#ff00aa',
      accentColor: '#ffffff',
      interiorColor: '#ff88cc',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'Corrupted geometry and unstable lanes demand quick reflexes and reroutes.',
      difficulty: 'expert',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 65000,
      timeLimitSeconds: 105,
      timeoutPenaltyMultiplier: 0.42,
      unlockedBy: 'SINGULARITY_WELL',
      theme: 'glitch',
      visualTheme: { primary: 'MATRIX', accent: 'CYAN', surfaceTint: 'GLASS' },
    },
  },
  {
    id: AdventureTrackType.RETRO_WAVE_HILLS,
    startAnchor: { x: 0, y: 5, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/RETRO_WAVE_HILLS.json',
    zone: {
      name: 'Retro Wave Hills',
      storyText: 'ENTERING: RETRO WAVE\n\nCruise the neon sunset...',
      videoUrl: 'videos/zones/retrowave_intro.mp4',
      musicTrackId: 'retrowave-hills',
      primaryColor: '#ff66aa',
      accentColor: '#00ccff',
      interiorColor: '#ff88cc',
      isMajorTransition: false,
      glowIntensity: 1.2,
    },
    catalog: {
      description: 'A neon sunset cruise — rolling hills and wide banked curves after the Spire.',
      difficulty: 'medium',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 70000,
      timeLimitSeconds: 130,
      timeoutPenaltyMultiplier: 0.50,
      unlockedBy: 'GLITCH_SPIRE',
      theme: 'retrowave',
      visualTheme: { primary: 'MAGENTA', accent: 'CYAN', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.CHRONO_CORE,
    startAnchor: { x: 0, y: 15, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/CHRONO_CORE.json',
    zone: {
      name: 'Chrono Core',
      storyText: 'TEMPORAL ANOMALY\n\nTime flows differently here...',
      videoUrl: 'videos/zones/chrono_intro.mp4',
      musicTrackId: 'chrono-core',
      primaryColor: '#00ffcc',
      accentColor: '#ff6600',
      interiorColor: '#44ffdd',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
    catalog: {
      description: 'A clockwork arena — ride two counter-rotating gears to reach the escapement.',
      difficulty: 'hard',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 90000,
      timeLimitSeconds: 100,
      timeoutPenaltyMultiplier: 0.42,
      unlockedBy: 'HYPER_DRIFT',
      theme: 'clockwork',
      visualTheme: { primary: 'GOLD', accent: 'AMBIENT', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.HYPER_DRIFT,
    startAnchor: { x: 0, y: 15, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/HYPER_DRIFT.json',
    zone: {
      name: 'Hyper Drift',
      storyText: 'HYPER VELOCITY\n\nHold on tight...',
      videoUrl: 'videos/zones/hyper_drift_intro.mp4',
      musicTrackId: 'hyper-drift',
      primaryColor: '#66ffff',
      accentColor: '#ff3366',
      interiorColor: '#88ffff',
      isMajorTransition: false,
      glowIntensity: 1.5,
    },
    catalog: {
      description: 'Full-throttle banked drifting through a corkscrew loop and a long jump.',
      difficulty: 'hard',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 85000,
      timeLimitSeconds: 140,
      timeoutPenaltyMultiplier: 0.48,
      unlockedBy: 'POLYCHROME_VOID',
      theme: 'hyper-drift',
      visualTheme: { primary: 'CYAN', accent: 'ALERT', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.PACHINKO_SPIRE,
    startAnchor: { x: 0, y: 30, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/PACHINKO_SPIRE.json',
    zone: {
      name: 'Pachinko Spire',
      storyText: 'ENTERING: PACHINKO SPIRE\n\nThe vertical descent awaits...',
      videoUrl: 'videos/zones/pachinko_spire_intro.mp4',
      musicTrackId: 'pachinko-spire',
      primaryColor: '#ffcc00',
      accentColor: '#ff2244',
      interiorColor: '#ffdd44',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'Bounce through a classic pin field tower. High-risk, high-reward gameplay.',
      difficulty: 'hard',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 38000,
      timeLimitSeconds: 75,
      timeoutPenaltyMultiplier: 0.40,
      unlockedBy: 'NEON_HELIX',
      theme: 'retro',
      visualTheme: { primary: 'GOLD', accent: 'ALERT', surfaceTint: 'PLAYFIELD' },
    },
  },
]
