/**
 * Per-track manifest definitions — the single registration surface for a track.
 *
 * One entry per AdventureTrackType carries its portal anchor, zone theming,
 * optional campaign catalog metadata, and its build dispatch: either a TS
 * `builder` function or a `dataPath` pointing at declarative JSON.
 */

import { AdventureTrackType } from '../adventure-types'
import type { TrackManifest } from './track-manifest-types'
import { buildNeonHelix } from '../tracks/neon-helix'
import { buildCyberCore } from '../tracks/cyber-core'
import { buildPachinkoHall } from '../tracks/pachinko-hall'
import { buildPachinkoSpire } from '../tracks/pachinko-spire'
import { buildOrbitalJunkyard } from '../tracks/orbital-junkyard'
import { buildPrismPathway } from '../tracks/prism-pathway'
import { buildMagneticStorage } from '../tracks/magnetic-storage'
import { buildNeuralNetwork } from '../tracks/neural-network'
import { buildNeonStronghold } from '../tracks/neon-stronghold'
import { buildCasinoHeist } from '../tracks/casino-heist'
import { buildCpuCore } from '../tracks/cpu-core'
import { buildBioHazardLab } from '../tracks/bio-hazard-lab'
import { buildGravityForge } from '../tracks/gravity-forge'
import { buildSynthwaveSurf } from '../tracks/synthwave-surf'
import { buildTeslaTower } from '../tracks/tesla-tower'
import { buildNeonSkyline } from '../tracks/neon-skyline'
import { buildPolychromeVoid } from '../tracks/polychrome-void'

export const MANIFEST_DATA: TrackManifest[] = [
  {
    id: AdventureTrackType.NEON_HELIX,
    startAnchor: { x: 0, y: 2, z: 8 },
    buildKind: 'ts',
    builder: buildNeonHelix,
    zone: {
      name: 'Neon Helix',
      storyText: 'ENTERING: NEON HELIX\n\nThe spiral descent begins...',
      videoUrl: 'videos/zones/neon_helix_intro.mp4',
      musicTrackId: 'neon-helix',
      primaryColor: '#00d9ff',
      accentColor: '#ff00aa',
      interiorColor: '#00ffff',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
    catalog: {
      description: 'A classic descent through spiraling neon light. Perfect for beginners.',
      difficulty: 'easy',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 50000,
      timeLimitSeconds: 120,
      timeoutPenaltyMultiplier: 0.55,
      theme: 'cyber-neon',
      visualTheme: { primary: 'CYAN', accent: 'MAGENTA', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.PACHINKO_HALL,
    startAnchor: { x: 0, y: 8, z: 4 },
    buildKind: 'ts',
    builder: buildPachinkoHall,
    zone: {
      name: 'Pachinko Hall',
      storyText: 'ENTERING: PACHINKO HALL\n\nThe neon parlor opens — follow the pin lanes to the exit arch...',
      videoUrl: 'videos/zones/pachinko_hall_intro.mp4',
      musicTrackId: 'pachinko-hall',
      primaryColor: '#ffdd00',
      accentColor: '#ff66cc',
      interiorColor: '#ffaa00',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'A neon parlor corridor — pin lanes, conveyor currents, and machine alcoves lead to the exit arch.',
      difficulty: 'easy',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 40000,
      timeLimitSeconds: 100,
      timeoutPenaltyMultiplier: 0.50,
      unlockedBy: 'NEON_HELIX',
      theme: 'pachinko-neon',
      visualTheme: { primary: 'GOLD', accent: 'MAGENTA', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.CYBER_CORE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildCyberCore,
    zone: {
      name: 'Cyber Core',
      storyText: 'ENTERING: CYBER CORE\n\nDescending into the digital depths...',
      videoUrl: 'videos/zones/cyber_core_intro.mp4',
      musicTrackId: 'cyber-core',
      primaryColor: '#8800ff',
      accentColor: '#00d9ff',
      interiorColor: '#aa44ff',
      isMajorTransition: true,
      glowIntensity: 1.1,
    },
    catalog: {
      description: 'Fast-paced vertical descent through a digital core. Requires precision timing.',
      difficulty: 'medium',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 45000,
      timeLimitSeconds: 90,
      timeoutPenaltyMultiplier: 0.45,
      unlockedBy: 'PACHINKO_HALL',
      theme: 'digital',
      visualTheme: { primary: 'MAGENTA', accent: 'CYAN', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.QUANTUM_GRID,
    startAnchor: { x: 0, y: 10, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/QUANTUM_GRID.json',
    zone: {
      name: 'Quantum Grid',
      storyText: 'ENTERING: QUANTUM GRID\n\nNavigate the probability maze...',
      videoUrl: 'videos/zones/quantum_grid_intro.mp4',
      musicTrackId: 'quantum-grid',
      primaryColor: '#00ff44',
      accentColor: '#ffffff',
      interiorColor: '#88ffaa',
      isMajorTransition: true,
      glowIntensity: 1.5,
    },
    catalog: {
      description: 'Navigate a complex maze of quantum pathways. The ultimate puzzle challenge.',
      difficulty: 'hard',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 80000,
      timeLimitSeconds: 150,
      timeoutPenaltyMultiplier: 0.50,
      unlockedBy: 'CYBER_CORE',
      theme: 'quantum',
      visualTheme: { primary: 'PURPLE', accent: 'WHITE', surfaceTint: 'GLASS' },
    },
  },
  {
    id: AdventureTrackType.SINGULARITY_WELL,
    startAnchor: { x: 0, y: 25, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/SINGULARITY_WELL.json',
    zone: {
      name: 'Singularity Well',
      storyText: 'WARNING: GRAVITY ANOMALY\n\nApproaching event horizon...',
      videoUrl: 'videos/zones/singularity_intro.mp4',
      musicTrackId: 'singularity-well',
      primaryColor: '#ff4400',
      accentColor: '#ff0000',
      interiorColor: '#ff6622',
      isMajorTransition: true,
      glowIntensity: 1.6,
    },
    catalog: {
      description: 'Enter a black hole. Gravity pulls everything inward. Expert only.',
      difficulty: 'expert',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 100000,
      timeLimitSeconds: 180,
      timeoutPenaltyMultiplier: 0.35,
      unlockedBy: 'QUANTUM_GRID',
      theme: 'cosmic',
      visualTheme: { primary: 'ALERT', accent: 'AMBIENT', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.GLITCH_SPIRE,
    startAnchor: { x: 0, y: 10, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/GLITCH_SPIRE.json',
    zone: {
      name: 'Glitch Spire',
      storyText: 'ALERT: REALITY UNSTABLE\n\nGlitch corruption detected...',
      videoUrl: 'videos/zones/glitch_spire_intro.mp4',
      musicTrackId: 'glitch-spire',
      primaryColor: '#ff00aa',
      accentColor: '#ffffff',
      interiorColor: '#ff88cc',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'Corrupted geometry and unstable lanes demand quick reflexes and reroutes.',
      difficulty: 'expert',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 65000,
      timeLimitSeconds: 105,
      timeoutPenaltyMultiplier: 0.42,
      unlockedBy: 'SINGULARITY_WELL',
      theme: 'glitch',
      visualTheme: { primary: 'MATRIX', accent: 'CYAN', surfaceTint: 'GLASS' },
    },
  },
  {
    id: AdventureTrackType.RETRO_WAVE_HILLS,
    startAnchor: { x: 0, y: 5, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/RETRO_WAVE_HILLS.json',
    zone: {
      name: 'Retro Wave Hills',
      storyText: 'ENTERING: RETRO WAVE\n\nCruise the neon sunset...',
      videoUrl: 'videos/zones/retrowave_intro.mp4',
      musicTrackId: 'retrowave-hills',
      primaryColor: '#ff66aa',
      accentColor: '#00ccff',
      interiorColor: '#ff88cc',
      isMajorTransition: false,
      glowIntensity: 1.2,
    },
    catalog: {
      description: 'A neon sunset cruise — rolling hills and wide banked curves after the Spire.',
      difficulty: 'medium',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 70000,
      timeLimitSeconds: 130,
      timeoutPenaltyMultiplier: 0.50,
      unlockedBy: 'GLITCH_SPIRE',
      theme: 'retrowave',
      visualTheme: { primary: 'MAGENTA', accent: 'CYAN', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.CHRONO_CORE,
    startAnchor: { x: 0, y: 15, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/CHRONO_CORE.json',
    zone: {
      name: 'Chrono Core',
      storyText: 'TEMPORAL ANOMALY\n\nTime flows differently here...',
      videoUrl: 'videos/zones/chrono_intro.mp4',
      musicTrackId: 'chrono-core',
      primaryColor: '#00ffcc',
      accentColor: '#ff6600',
      interiorColor: '#44ffdd',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
    catalog: {
      description: 'A clockwork arena — ride two counter-rotating gears to reach the escapement.',
      difficulty: 'hard',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 90000,
      timeLimitSeconds: 100,
      timeoutPenaltyMultiplier: 0.42,
      unlockedBy: 'HYPER_DRIFT',
      theme: 'clockwork',
      visualTheme: { primary: 'GOLD', accent: 'AMBIENT', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.HYPER_DRIFT,
    startAnchor: { x: 0, y: 15, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/HYPER_DRIFT.json',
    zone: {
      name: 'Hyper Drift',
      storyText: 'HYPER VELOCITY\n\nHold on tight...',
      videoUrl: 'videos/zones/hyper_drift_intro.mp4',
      musicTrackId: 'hyper-drift',
      primaryColor: '#66ffff',
      accentColor: '#ff3366',
      interiorColor: '#88ffff',
      isMajorTransition: false,
      glowIntensity: 1.5,
    },
    catalog: {
      description: 'Full-throttle banked drifting through a corkscrew loop and a long jump.',
      difficulty: 'hard',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 85000,
      timeLimitSeconds: 140,
      timeoutPenaltyMultiplier: 0.48,
      unlockedBy: 'POLYCHROME_VOID',
      theme: 'hyper-drift',
      visualTheme: { primary: 'CYAN', accent: 'ALERT', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.PACHINKO_SPIRE,
    startAnchor: { x: 0, y: 30, z: 0 },
    buildKind: 'ts',
    builder: buildPachinkoSpire,
    zone: {
      name: 'Pachinko Spire',
      storyText: 'ENTERING: PACHINKO SPIRE\n\nThe vertical descent awaits...',
      videoUrl: 'videos/zones/pachinko_spire_intro.mp4',
      musicTrackId: 'pachinko-spire',
      primaryColor: '#ffcc00',
      accentColor: '#ff2244',
      interiorColor: '#ffdd44',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'Bounce through a classic pin field tower. High-risk, high-reward gameplay.',
      difficulty: 'hard',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 38000,
      timeLimitSeconds: 75,
      timeoutPenaltyMultiplier: 0.40,
      unlockedBy: 'NEON_HELIX',
      theme: 'retro',
      visualTheme: { primary: 'GOLD', accent: 'ALERT', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.ORBITAL_JUNKYARD,
    startAnchor: { x: 0, y: 15, z: 0 },
    buildKind: 'ts',
    builder: buildOrbitalJunkyard,
    zone: {
      name: 'Orbital Junkyard',
      storyText: 'ORBITAL DEBRIS FIELD\n\nNavigate the scrap sector...',
      videoUrl: 'videos/zones/junkyard_intro.mp4',
      musicTrackId: 'orbital-junkyard',
      primaryColor: '#aaaaaa',
      accentColor: '#ff6600',
      interiorColor: '#cccccc',
      isMajorTransition: true,
      glowIntensity: 0.9,
    },
  },
  {
    id: AdventureTrackType.FIREWALL_BREACH,
    startAnchor: { x: 0, y: 25, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/FIREWALL_BREACH.json',
    zone: {
      name: 'Firewall Breach',
      storyText: 'WARNING: SECURITY BREACH\n\nIntrusion detected...',
      videoUrl: 'videos/zones/firewall_intro.mp4',
      musicTrackId: 'firewall-breach',
      primaryColor: '#ff0000',
      accentColor: '#ffaa00',
      interiorColor: '#ff4444',
      isMajorTransition: true,
      glowIntensity: 1.7,
    },
    catalog: {
      description: 'Campaign finale — punch through two security layers to reach root access.',
      difficulty: 'expert',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 120000,
      timeLimitSeconds: 165,
      timeoutPenaltyMultiplier: 0.36,
      unlockedBy: 'CASINO_HEIST',
      theme: 'firewall',
      visualTheme: { primary: 'ALERT', accent: 'CYAN', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.CPU_CORE,
    startAnchor: { x: 0, y: 15, z: 0 },
    buildKind: 'ts',
    builder: buildCpuCore,
    zone: {
      name: 'CPU Core',
      storyText: 'ENTERING: CPU CORE\n\nThe central processor awaits...',
      videoUrl: 'videos/zones/cpu_intro.mp4',
      musicTrackId: 'cpu-core',
      primaryColor: '#00ff00',
      accentColor: '#88ff00',
      interiorColor: '#44ff44',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
  },
  {
    id: AdventureTrackType.CRYO_CHAMBER,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/CRYO_CHAMBER.json',
    zone: {
      name: 'Cryo Chamber',
      storyText: 'CRYOGENIC ZONE\n\nTemperature dropping...',
      videoUrl: 'videos/zones/cryo_intro.mp4',
      musicTrackId: 'cryo-chamber',
      primaryColor: '#00ccff',
      accentColor: '#ffffff',
      interiorColor: '#88ddff',
      isMajorTransition: true,
      glowIntensity: 1.2,
    },
    catalog: {
      description: 'Near-frictionless ice — a slalom of pillars and an avalanche sweep.',
      difficulty: 'expert',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 95000,
      timeLimitSeconds: 150,
      timeoutPenaltyMultiplier: 0.40,
      unlockedBy: 'CHRONO_CORE',
      theme: 'cryo',
      visualTheme: { primary: 'WHITE', accent: 'CYAN', surfaceTint: 'GLASS' },
    },
  },
  {
    id: AdventureTrackType.BIO_HAZARD_LAB,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildBioHazardLab,
    zone: {
      name: 'Bio Hazard Lab',
      storyText: 'BIOHAZARD WARNING\n\nToxic materials present...',
      videoUrl: 'videos/zones/biohazard_intro.mp4',
      musicTrackId: 'bio-hazard',
      primaryColor: '#44ff00',
      accentColor: '#ffcc00',
      interiorColor: '#66ff22',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
  },
  {
    id: AdventureTrackType.GRAVITY_FORGE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildGravityForge,
    zone: {
      name: 'Gravity Forge',
      storyText: 'GRAVITY FORGE\n\nHeavy industry sector...',
      videoUrl: 'videos/zones/forge_intro.mp4',
      musicTrackId: 'gravity-forge',
      primaryColor: '#ff6600',
      accentColor: '#ffcc00',
      interiorColor: '#ff8844',
      isMajorTransition: true,
      glowIntensity: 1.5,
    },
  },
  {
    id: AdventureTrackType.TIDAL_NEXUS,
    startAnchor: { x: 0, y: 25, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/TIDAL_NEXUS.json',
    zone: {
      name: 'Tidal Nexus',
      storyText: 'TIDAL NEXUS\n\nFlow with the current...',
      videoUrl: 'videos/zones/tidal_intro.mp4',
      musicTrackId: 'tidal-nexus',
      primaryColor: '#0088ff',
      accentColor: '#00ffcc',
      interiorColor: '#44aaff',
      isMajorTransition: false,
      glowIntensity: 1.2,
    },
    catalog: {
      description: 'Post-finale spillway — turbine spin, riptide bank, and an abyssal drop basin.',
      difficulty: 'expert',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 125000,
      timeLimitSeconds: 170,
      timeoutPenaltyMultiplier: 0.35,
      unlockedBy: 'FIREWALL_BREACH',
      theme: 'tidal',
      visualTheme: { primary: 'CYAN', accent: 'WHITE', surfaceTint: 'GLASS' },
    },
  },
  {
    id: AdventureTrackType.DIGITAL_ZEN_GARDEN,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/DIGITAL_ZEN_GARDEN.json',
    zone: {
      name: 'Digital Zen Garden',
      storyText: 'ZEN GARDEN\n\nFind your center...',
      videoUrl: 'videos/zones/zen_intro.mp4',
      musicTrackId: 'zen-garden',
      primaryColor: '#88ffaa',
      accentColor: '#ff88aa',
      interiorColor: '#aaffcc',
      isMajorTransition: false,
      glowIntensity: 0.8,
    },
    catalog: {
      description: 'Raked sand lanes, a low-friction stream bend, and a moon-bridge shrine basin.',
      difficulty: 'medium',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 60000,
      timeLimitSeconds: 110,
      timeoutPenaltyMultiplier: 0.48,
      unlockedBy: 'SOLAR_FLARE',
      theme: 'zen',
      visualTheme: { primary: 'WHITE', accent: 'MAGENTA', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.SYNTHWAVE_SURF,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildSynthwaveSurf,
    zone: {
      name: 'Synthwave Surf',
      storyText: 'SURF THE WAVES\n\nCatch the perfect break...',
      videoUrl: 'videos/zones/surf_intro.mp4',
      musicTrackId: 'synthwave-surf',
      primaryColor: '#ff88cc',
      accentColor: '#00ddff',
      interiorColor: '#ffaadd',
      isMajorTransition: false,
      glowIntensity: 1.1,
    },
  },
  {
    id: AdventureTrackType.SOLAR_FLARE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'json',
    dataPath: './track-data/SOLAR_FLARE.json',
    zone: {
      name: 'Solar Flare',
      storyText: 'WARNING: SOLAR FLARE\n\nRadiation levels high...',
      videoUrl: 'videos/zones/solar_intro.mp4',
      musicTrackId: 'solar-flare',
      primaryColor: '#ffaa00',
      accentColor: '#ff4400',
      interiorColor: '#ffcc44',
      isMajorTransition: true,
      glowIntensity: 1.6,
    },
    catalog: {
      description: 'Coronal launch, sunspot straight, and a solar-wind sweep into the fusion core.',
      difficulty: 'hard',
      modeType: 'EXTENDED_MAP',
      recommendedScore: 115000,
      timeLimitSeconds: 155,
      timeoutPenaltyMultiplier: 0.36,
      unlockedBy: 'TIDAL_NEXUS',
      theme: 'solar',
      visualTheme: { primary: 'GOLD', accent: 'ALERT', surfaceTint: 'PLAYFIELD_DEEP' },
    },
  },
  {
    id: AdventureTrackType.PRISM_PATHWAY,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildPrismPathway,
    zone: {
      name: 'Prism Pathway',
      storyText: 'PRISM PATHWAY\n\nLight refracts infinitely...',
      videoUrl: 'videos/zones/prism_intro.mp4',
      musicTrackId: 'prism-path',
      primaryColor: '#ff00ff',
      accentColor: '#00ffff',
      interiorColor: '#ff88ff',
      isMajorTransition: true,
      glowIntensity: 1.5,
    },
  },
  {
    id: AdventureTrackType.MAGNETIC_STORAGE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildMagneticStorage,
    zone: {
      name: 'Magnetic Storage',
      storyText: 'MAGNETIC STORAGE\n\nData streams flowing...',
      videoUrl: 'videos/zones/magnetic_intro.mp4',
      musicTrackId: 'magnetic',
      primaryColor: '#aa44ff',
      accentColor: '#00ff88',
      interiorColor: '#cc88ff',
      isMajorTransition: false,
      glowIntensity: 1.2,
    },
  },
  {
    id: AdventureTrackType.NEURAL_NETWORK,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildNeuralNetwork,
    zone: {
      name: 'Neural Network',
      storyText: 'NEURAL NETWORK\n\nSynaptic pathways active...',
      videoUrl: 'videos/zones/neural_intro.mp4',
      musicTrackId: 'neural',
      primaryColor: '#ff66aa',
      accentColor: '#aa66ff',
      interiorColor: '#ff99cc',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
  },
  {
    id: AdventureTrackType.NEON_STRONGHOLD,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildNeonStronghold,
    zone: {
      name: 'Neon Stronghold',
      storyText: 'NEON STRONGHOLD\n\nThe fortress awaits...',
      videoUrl: 'videos/zones/stronghold_intro.mp4',
      musicTrackId: 'stronghold',
      primaryColor: '#00aaff',
      accentColor: '#ff00cc',
      interiorColor: '#44ccff',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'Optional siege route — drawbridges and portcullis gates ring the courtyard.',
      difficulty: 'hard',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 55000,
      timeLimitSeconds: 95,
      timeoutPenaltyMultiplier: 0.45,
      unlockedBy: 'PACHINKO_HALL',
      theme: 'fortress',
      visualTheme: { primary: 'PURPLE', accent: 'GOLD', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.CASINO_HEIST,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildCasinoHeist,
    zone: {
      name: 'Casino Heist',
      storyText: 'CASINO HEIST\n\nHigh stakes ahead...',
      videoUrl: 'videos/zones/casino_intro.mp4',
      musicTrackId: 'casino',
      primaryColor: '#ffcc00',
      accentColor: '#ff0044',
      interiorColor: '#ffdd44',
      isMajorTransition: true,
      glowIntensity: 1.5,
    },
    catalog: {
      description: 'Chip stacks, a live roulette wheel, and slot gates guarding the vault.',
      difficulty: 'expert',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 105000,
      timeLimitSeconds: 90,
      timeoutPenaltyMultiplier: 0.38,
      unlockedBy: 'CRYO_CHAMBER',
      theme: 'casino',
      visualTheme: { primary: 'GOLD', accent: 'ALERT', surfaceTint: 'PLAYFIELD' },
    },
  },
  {
    id: AdventureTrackType.TESLA_TOWER,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildTeslaTower,
    zone: {
      name: 'Tesla Tower',
      storyText: 'TESLA TOWER\n\nHigh voltage zone...',
      videoUrl: 'videos/zones/tesla_intro.mp4',
      musicTrackId: 'tesla',
      primaryColor: '#aa66ff',
      accentColor: '#00ffff',
      interiorColor: '#cc99ff',
      isMajorTransition: true,
      glowIntensity: 1.6,
    },
  },
  {
    id: AdventureTrackType.NEON_SKYLINE,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildNeonSkyline,
    zone: {
      name: 'Neon Skyline',
      storyText: 'NEON SKYLINE\n\nThe city never sleeps...',
      videoUrl: 'videos/zones/skyline_intro.mp4',
      musicTrackId: 'skyline',
      primaryColor: '#0088ff',
      accentColor: '#ff00aa',
      interiorColor: '#44aaff',
      isMajorTransition: true,
      glowIntensity: 1.3,
    },
  },
  {
    id: AdventureTrackType.POLYCHROME_VOID,
    startAnchor: { x: 0, y: 20, z: 0 },
    buildKind: 'ts',
    builder: buildPolychromeVoid,
    zone: {
      name: 'Polychrome Void',
      storyText: 'THE POLYCHROME VOID\n\nBeyond the spectrum...',
      videoUrl: 'videos/zones/polychrome_intro.mp4',
      musicTrackId: 'polychrome',
      primaryColor: '#ffffff',
      accentColor: '#ff00ff',
      interiorColor: '#f0f0f0',
      isMajorTransition: true,
      glowIntensity: 1.4,
    },
    catalog: {
      description: 'A colour-logic arena — chroma gates only pass the matching ball state.',
      difficulty: 'hard',
      modeType: 'STATIONARY_TABLE',
      recommendedScore: 75000,
      timeLimitSeconds: 95,
      timeoutPenaltyMultiplier: 0.44,
      unlockedBy: 'RETRO_WAVE_HILLS',
      theme: 'chroma-puzzle',
      visualTheme: { primary: 'WHITE', accent: 'MAGENTA', surfaceTint: 'GLASS' },
    },
  },
]
