import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'
import { importX, createNodeResolver } from 'eslint-plugin-import-x'

export default defineConfig([
  // dev-dist is vite-plugin-pwa's dev output — regenerated by any `npm run dev`,
  // including Playwright's webServer. It is gitignored, but flat config does not
  // read .gitignore, so without this a local e2e run leaves generated workbox
  // bundles behind and `npm run lint` fails on them.
  globalIgnores(['dist', 'dev-dist', 'native/build*', 'native/build/**']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
      }],
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message:
            'Use deep imports (@babylonjs/core/Meshes/mesh, etc.) for tree-shaking. ' +
            'Run node scripts/codemod-babylon-deep-imports.mjs if needed.',
        }],
      }],
    },
  },
  // Type-aware rules (#441): no-floating-promises, no-misused-promises, the no-unsafe-*
  // family, etc. Scoped to src/, which tsconfig.app.json / tsconfig.worker.json cover;
  // tests, scripts and tool configs are in no tsconfig and keep the untyped preset above.
  {
    files: ['src/**/*.ts'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // `async` without `await` is deliberate here: it guarantees a Promise return and turns a
      // synchronous throw into a rejection for handlers/hooks typed `() => Promise<void>`.
      '@typescript-eslint/require-await': 'off',
    },
  },
  // Lock in the current zero-cycle import graph (#322, #441). Type-only imports are erased and
  // ignored by the rule; lazy `import()` edges are what deliberately break runtime cycles.
  {
    files: ['src/**/*.ts'],
    plugins: { 'import-x': importX },
    settings: {
      // The rule only follows files whose extension is listed here (default: .js/.mjs/.cjs).
      'import-x/extensions': ['.ts', '.tsx', '.js', '.mjs'],
      'import-x/resolver-next': [
        createNodeResolver({ extensions: ['.ts', '.tsx', '.js', '.mjs', '.json'] }),
      ],
    },
    rules: {
      'import-x/no-cycle': ['error', { maxDepth: Infinity, allowUnsafeDynamicCyclicDependency: true }],
    },
  },
  // Timers in long-lived systems go through a TimerScope (#441) so dispose() can cancel them: a
  // bare setTimeout outlives its owner and later touches a torn-down scene, DOM node or field.
  // `timers.setTimeout(…)` / `scope.setTimeout(…)` are member calls on a non-global object and
  // pass. A bare call that is genuinely safe (touches only captured nodes, guards its own
  // state) takes `// eslint-disable-next-line no-restricted-syntax -- <why>`.
  // engine/, wasm/, config/, replay/ and cabinet/ are bootstrap/worker code and stay outside.
  {
    files: [
      'src/game/**/*.ts',
      'src/game-elements/**/*.ts',
      'src/effects/**/*.ts',
      'src/objects/**/*.ts',
      'src/display/**/*.ts',
      'src/audio/**/*.ts',
      'src/adventure/**/*.ts',
    ],
    // PathMechanicsManager is never instantiated by the shipped game; revisit when it is wired in.
    ignores: ['src/game-elements/path-mechanics/**'],
    rules: {
      'no-restricted-syntax': ['error',
        {
          selector: "CallExpression[callee.type='Identifier'][callee.name=/^(setTimeout|setInterval|requestAnimationFrame)$/]",
          message: 'Bare timers outlive dispose(). Schedule through a TimerScope (src/core/timers.ts: game.timers or the owner\'s own scope).',
        },
        {
          selector: "CallExpression[callee.type='MemberExpression'][callee.object.name=/^(window|globalThis)$/][callee.property.name=/^(setTimeout|setInterval|requestAnimationFrame)$/]",
          message: 'Bare timers outlive dispose(). Schedule through a TimerScope (src/core/timers.ts: game.timers or the owner\'s own scope).',
        },
      ],
    },
  },
  // `!` on an indexed read looks redundant until noUncheckedIndexedAccess is on for the whole
  // project. These directories are already held to it by `npm run check:index-strict`, where the
  // `!` is load-bearing, so don't let the autofixer strip it (#441).
  {
    files: ['src/core/**/*.ts', 'src/wasm/**/*.ts', 'src/game/physics/**/*.ts'],
    rules: { '@typescript-eslint/no-unnecessary-type-assertion': 'off' },
  },
  // ── Layering (#322) ───────────────────────────────────────────────────────
  // Dependencies point one way: core <- game-elements <- game. These rules make
  // that mechanical instead of a convention people have to remember.
  //
  //   src/core/        kernel — EventBus, asset URLs. No Babylon, no upper layers.
  //   src/game-elements/  low-level systems. May use core, never the game layer.
  //   src/game/        high-level orchestration. May use anything below.
  {
    files: ['src/game-elements/**/*.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message:
            'Use deep imports (@babylonjs/core/Meshes/mesh, etc.) for tree-shaking. ' +
            'Run node scripts/codemod-babylon-deep-imports.mjs if needed.',
        }],
        patterns: [{
          group: ['../game/*', '../game/**', '**/src/game/*', '**/src/game/**'],
          message:
            'game-elements must not import from the game layer (inverted dependency). ' +
            'EventBus and asset URLs live in src/core/. If you need a type from a game-layer ' +
            'class, declare the shape you actually use locally — see TrackThemingMapSource.',
        }],
      }],
    },
  },
  // Config purity: no Babylon, no game-elements. The display barrel is banned;
  // display-slot.ts is the sole exception (slot enums needed at runtime).
  {
    files: ['src/config/**/*.ts'],
    ignores: ['src/config/display-slot.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message: 'src/config must stay engine-free (Worker-safe).',
        }],
        patterns: [
          {
            group: ['@babylonjs/**'],
            message: 'src/config must stay engine-free (Worker-safe).',
          },
          {
            group: ['**/game-elements', '**/game-elements/**', '../game-elements', '../game-elements/**'],
            message: 'src/config must not import game-elements.',
          },
          {
            group: ['**/display', '../display', '../display/**', '**/display/**'],
            message:
              'src/config may import slot enums only from display/slot-types, and only in display-slot.ts.',
          },
        ],
      }],
    },
  },
  {
    files: ['src/config/display-slot.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message: 'src/config must stay engine-free (Worker-safe).',
        }],
        patterns: [
          {
            group: ['@babylonjs/**'],
            message: 'src/config must stay engine-free (Worker-safe).',
          },
          {
            group: ['**/game-elements', '**/game-elements/**', '../game-elements', '../game-elements/**'],
            message: 'src/config must not import game-elements.',
          },
          {
            group: ['../display/index', '../display/index.ts'],
            message: 'Import slot-types deep path only, not the display barrel.',
          },
        ],
      }],
    },
  },
  {
    files: ['src/core/**/*.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message:
            'src/core must stay engine-free so it can be used and unit-tested without ' +
            'standing up Babylon. Anything needing Color3 etc. belongs a layer up.',
        }],
        patterns: [
          {
            group: ['../game/*', '../game/**', '**/src/game/*', '**/src/game/**'],
            message: 'src/core is the kernel — it must not depend on the game layer.',
          },
          {
            // Event-map payload types such as GameState still live in game-elements
            // (DisplayState moved to src/display/display-types). Types are erased,
            // so they create no runtime edge; a runtime import would, and is what
            // this blocks.
            group: ['../game-elements/*', '../game-elements/**'],
            allowTypeImports: true,
            message:
              'src/core may reference game-elements types (erased at compile time) but must ' +
              'not import runtime values from them.',
          },
        ],
      }],
    },
  },

  // game-elements barrel must not re-export sibling packages (inverted barrel).
  {
    files: ['src/game-elements/index.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message:
            'Use deep imports (@babylonjs/core/Meshes/mesh, etc.) for tree-shaking. ' +
            'Run node scripts/codemod-babylon-deep-imports.mjs if needed.',
        }],
        patterns: [
          {
            group: ['../game/*', '../game/**', '**/src/game/*', '**/src/game/**'],
            message:
              'game-elements must not import from the game layer (inverted dependency).',
          },
          {
            group: [
              '../display', '../display/**',
              '../effects', '../effects/**',
              '../objects', '../objects/**',
              '../cabinet', '../cabinet/**',
              '../shaders', '../shaders/**',
              '../materials', '../materials/**',
              '../core/seeded-rng',
              '../adventure', '../adventure/**',
            ],
            message:
              'game-elements/index.ts must not re-export sibling packages. Import them from their canonical barrels.',
          },
        ],
      }],
    },
  },

  // Playwright E2E and Vitest spec files: relax no-explicit-any since page.evaluate()
  // callbacks cross a browser context boundary where window.game is untyped.
  {
    files: ['tests/**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
])
