import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // dev-dist is vite-plugin-pwa's dev output — regenerated by any `npm run dev`,
  // including Playwright's webServer. It is gitignored, but flat config does not
  // read .gitignore, so without this a local e2e run leaves generated workbox
  // bundles behind and `npm run lint` fails on them.
  globalIgnores(['dist', 'dev-dist', 'native/build']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
      }],
    },
  },
  // ── Layering (#322) ───────────────────────────────────────────────────────
  // Dependencies point one way: core <- game-elements <- game. These rules make
  // that mechanical instead of a convention people have to remember.
  //
  //   src/core/        kernel — EventBus, asset URLs. No Babylon, no upper layers.
  //   src/game-elements/  low-level systems. May use core, never the game layer.
  //   src/game/        high-level orchestration. May use anything below.
  {
    files: ['src/game-elements/**/*.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        patterns: [{
          group: ['../game/*', '../game/**', '**/src/game/*', '**/src/game/**'],
          message:
            'game-elements must not import from the game layer (inverted dependency). ' +
            'EventBus and asset URLs live in src/core/. If you need a type from a game-layer ' +
            'class, declare the shape you actually use locally — see TrackThemingMapSource.',
        }],
      }],
    },
  },
  {
    files: ['src/core/**/*.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message:
            'src/core must stay engine-free so it can be used and unit-tested without ' +
            'standing up Babylon. Anything needing Color3 etc. belongs a layer up.',
        }],
        patterns: [
          {
            group: ['../game/*', '../game/**', '**/src/game/*', '**/src/game/**'],
            message: 'src/core is the kernel — it must not depend on the game layer.',
          },
          {
            // Event-map payload types (DisplayState, GameState, ...) still live in
            // game-elements. Types are erased, so they create no runtime edge;
            // a runtime import would, and is what this blocks.
            group: ['../game-elements/*', '../game-elements/**'],
            allowTypeImports: true,
            message:
              'src/core may reference game-elements types (erased at compile time) but must ' +
              'not import runtime values from them.',
          },
        ],
      }],
    },
  },

  // Playwright E2E and Vitest spec files: relax no-explicit-any since page.evaluate()
  // callbacks cross a browser context boundary where window.game is untyped.
  {
    files: ['tests/**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
])
