import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // dev-dist is vite-plugin-pwa's dev output — regenerated by any `npm run dev`,
  // including Playwright's webServer. It is gitignored, but flat config does not
  // read .gitignore, so without this a local e2e run leaves generated workbox
  // bundles behind and `npm run lint` fails on them.
  globalIgnores(['dist', 'dev-dist', 'native/build*', 'native/build/**']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
      }],
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message:
            'Use deep imports (@babylonjs/core/Meshes/mesh, etc.) for tree-shaking. ' +
            'Run node scripts/codemod-babylon-deep-imports.mjs if needed.',
        }],
      }],
    },
  },
  // ── Layering (#322) ───────────────────────────────────────────────────────
  // Dependencies point one way: core <- game-elements <- game. These rules make
  // that mechanical instead of a convention people have to remember.
  //
  //   src/core/        kernel — EventBus, asset URLs. No Babylon, no upper layers.
  //   src/game-elements/  low-level systems. May use core, never the game layer.
  //   src/game/        high-level orchestration. May use anything below.
  {
    files: ['src/game-elements/**/*.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message:
            'Use deep imports (@babylonjs/core/Meshes/mesh, etc.) for tree-shaking. ' +
            'Run node scripts/codemod-babylon-deep-imports.mjs if needed.',
        }],
        patterns: [{
          group: ['../game/*', '../game/**', '**/src/game/*', '**/src/game/**'],
          message:
            'game-elements must not import from the game layer (inverted dependency). ' +
            'EventBus and asset URLs live in src/core/. If you need a type from a game-layer ' +
            'class, declare the shape you actually use locally — see TrackThemingMapSource.',
        }],
      }],
    },
  },
  // Config purity: no Babylon, no game-elements. The display barrel is banned;
  // display-slot.ts is the sole exception (slot enums needed at runtime).
  {
    files: ['src/config.ts', 'src/config/**/*.ts'],
    ignores: ['src/config/display-slot.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message: 'src/config must stay engine-free (Worker-safe).',
        }],
        patterns: [
          {
            group: ['@babylonjs/**'],
            message: 'src/config must stay engine-free (Worker-safe).',
          },
          {
            group: ['**/game-elements', '**/game-elements/**', '../game-elements', '../game-elements/**'],
            message: 'src/config must not import game-elements.',
          },
          {
            group: ['**/display', '../display', '../display/**', '**/display/**'],
            message:
              'src/config may import slot enums only from display/slot-types, and only in display-slot.ts.',
          },
        ],
      }],
    },
  },
  {
    files: ['src/config/display-slot.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message: 'src/config must stay engine-free (Worker-safe).',
        }],
        patterns: [
          {
            group: ['@babylonjs/**'],
            message: 'src/config must stay engine-free (Worker-safe).',
          },
          {
            group: ['**/game-elements', '**/game-elements/**', '../game-elements', '../game-elements/**'],
            message: 'src/config must not import game-elements.',
          },
          {
            group: ['../display/index', '../display/index.ts'],
            message: 'Import slot-types deep path only, not the display barrel.',
          },
        ],
      }],
    },
  },
  {
    files: ['src/core/**/*.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message:
            'src/core must stay engine-free so it can be used and unit-tested without ' +
            'standing up Babylon. Anything needing Color3 etc. belongs a layer up.',
        }],
        patterns: [
          {
            group: ['../game/*', '../game/**', '**/src/game/*', '**/src/game/**'],
            message: 'src/core is the kernel — it must not depend on the game layer.',
          },
          {
            // Event-map payload types (DisplayState, GameState, ...) still live in
            // game-elements. Types are erased, so they create no runtime edge;
            // a runtime import would, and is what this blocks.
            group: ['../game-elements/*', '../game-elements/**'],
            allowTypeImports: true,
            message:
              'src/core may reference game-elements types (erased at compile time) but must ' +
              'not import runtime values from them.',
          },
        ],
      }],
    },
  },

  // game-elements barrel must not re-export sibling packages (inverted barrel).
  {
    files: ['src/game-elements/index.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', {
        paths: [{
          name: '@babylonjs/core',
          message:
            'Use deep imports (@babylonjs/core/Meshes/mesh, etc.) for tree-shaking. ' +
            'Run node scripts/codemod-babylon-deep-imports.mjs if needed.',
        }],
        patterns: [
          {
            group: ['../game/*', '../game/**', '**/src/game/*', '**/src/game/**'],
            message:
              'game-elements must not import from the game layer (inverted dependency).',
          },
          {
            group: [
              '../display', '../display/**',
              '../effects', '../effects/**',
              '../objects', '../objects/**',
              '../cabinet', '../cabinet/**',
              '../shaders', '../shaders/**',
              '../materials', '../materials/**',
              '../core/seeded-rng',
              '../adventure', '../adventure/**',
            ],
            message:
              'game-elements/index.ts must not re-export sibling packages. Import them from their canonical barrels.',
          },
        ],
      }],
    },
  },

  // Playwright E2E and Vitest spec files: relax no-explicit-any since page.evaluate()
  // callbacks cross a browser context boundary where window.game is untyped.
  {
    files: ['tests/**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
])
