export {
  createEngine,
  isWebGPUEngine,
  resolveEngineCreationPlan,
  webgpuFeatureLevelsToTry,
  toWebGLEngineOptions,
  toWebGPUEngineOptions,
  attachGpuContextLogging,
  createWebGPUEngineWithFallback,
  GPU_DEGRADE_MARKER,
  type EngineCreationPlan,
  type WebGPUEngineLike,
  type WebGPUEngineFactory,
  type WebGPUCreationResult,
  type GpuContextLoggingDeps,
  DEBUG_LOSE_CONTEXT_GLOBAL,
  DEBUG_RESTORE_CONTEXT_GLOBAL,
} from './create-engine'
export {
  recordGpuDegrade,
  setActiveGpuFeatureLevel,
  getActiveGpuFeatureLevel,
  getGpuDegrades,
  countGpuDegrades,
  ensureGpuDegradeBuffer,
  ensureGpuProbe,
  recordGpuProbeEngine,
  recordGpuProbePostProcess,
  getGpuProbe,
  formatGpuProbeSummary,
  resetGpuDegradesForTests,
  GPU_DEGRADE_RING_SIZE,
  GPU_DEGRADE_GLOBAL,
  GPU_PROBE_GLOBAL,
  type GpuProbeSnapshot,
  type GpuDegradeEntry,
  type GpuDegradePath,
  type GpuDegradeFeatureLevel,
} from './gpu-degrade-telemetry'
export {
  GpuContextToast,
  GPU_CONTEXT_ATTRIBUTE,
  GPU_CONTEXT_TOAST_ID,
  GPU_CONTEXT_LOST_MESSAGE,
  GPU_CONTEXT_RESTORED_MESSAGE,
  RESTORED_TOAST_MS,
  RESTORED_TOAST_MS_REDUCED_MOTION,
  type GpuContextState,
  type GpuContextToastDeps,
} from './gpu-context-toast'
export {
  applyHardwareScaling,
  resolveEngineOptions,
  resolveHardwareScalingLevel,
  shouldForceLowQualityMobile,
  isMobileUserAgent,
  type PowerPreference,
  type GpuFeatureLevel,
  type ResolvedEngineOptions,
  type EngineOptionsContext,
  type MobileQualityHints,
} from './engine-options'
export {
  scheduleIdleWasmPreload,
  getPreloadedWasmModule,
  resetWasmPreloadForTests,
} from './wasm-idle-preload'
export { VisibilityManager, type VisibilityManagerDeps } from './visibility-manager'
